### ISSUE TITLE
Feature request - tag or/and release for new version

### ISSUE THREAD

**Issue by ja-pa** [clarkwang/sexpect#14]
Hi,
I'm trying to create sexpect [package for OpenWrt ](https://github.com/ja-pa/packages/commit/fd96670fbda3132409f72e1e2f46b63fc038890d) and it would be useful if there was tag or release (that would be even better).for specific version.

**Comment by clarkwang** [comment]
@ja-pa Created tag `v2.3.3` for the latest version. Please see if that meets your requirement. I'll tag future versions too.

**Comment by ja-pa** [comment]
Yes, that is it. Thank you!
I updated the OpenWrt package and I hope it will be accepted in OpenWrt upstream.
https://github.com/ja-pa/packages/commit/aeea5708831c65c1143a75535ec07dc6af3ff569

**Comment by clarkwang** [comment]
Thanks for the effort.
