### ISSUE TITLE
[v2.3.12] Add an option to pass a file descriptor to the "send" command

### ISSUE THREAD

**Issue by vaygr** [clarkwang/sexpect#33]
Inspired by [this](https://security.stackexchange.com/questions/177941/pass-password-to-gpg-via-script) so named pipes could be used.

Passing it to `-file` returns:

```
[ERROR] not a regular file: /dev/fd/63
```

Not sure if it can be combined or split into its own arg like `-file-fd`.

**Comment by vaygr** [comment]
Same as in the link in the description. I want to be able to pass `<(dmenu -P)` as an argument.

**Comment by clarkwang** [comment]
OK. Let me see if I can remove the regular file check.

**Comment by vaygr** [comment]
Another useful (somewhat related) thing would be to allow specifying `-` for `-file` to accept data from stdio. In both cases (named pipe and stdio) the 1024b limit can still be preserved, discarding everything else beyond that.

**Comment by clarkwang** [comment]
May be like this:

* `send -file FILE [-limit COUNT]`
  * *FILE* can be `-` which means *stdin*.
  * If `-limit COUNT` is not specified, *FILE* must be a regular file of size &le; 1024.
  * *COUNT* in range [1, 1024].
* `send -fd FD -limit COUNT`
  * `-limit` must be specified with `-fd`.
  * *COUNT* in range [1, 1024].
 
The idea is to make the behavior more explicit rather than silently discarding data so users would not be surprised.

**Comment by vaygr** [comment]
Yeah, I think that's great.

**Comment by clarkwang** [comment]
It's now available on the "devel" branch. Will merge to "master" after the doc is updated and tests are added.

**Comment by vaygr** [comment]
That's impressive, thanks! Testing it now:

```
$ ./sexpect -s /tmp/sp.sock send -fd <(dmenu) -limit 32
[ERROR] invalid number: /dev/fd/63
```

Probably makes sense to accept paths as well, not just fd by number?

**Comment by vaygr** [comment]
When I'm trying to use stdio, I have to hit extra <kbd>Enter</kbd> to make dmenu pop up:

```
./sexpect -s /tmp/sp.sock send -file - -limit 32 | dmenu

```

**Comment by clarkwang** [comment]
> That's impressive, thanks! Testing it now:
> 
> ```
> $ ./sexpect -s /tmp/sp.sock send -fd <(dmenu) -limit 32
> [ERROR] invalid number: /dev/fd/63
> ```
> 
> Probably makes sense to accept paths as well, not just fd by number?

Shell's `<(cmd)` is not a FD. It's a pathname, as is `/dev/fd/63` in the error message.

**Comment by clarkwang** [comment]
> When I'm trying to use stdio, I have to hit extra Enter to make dmenu pop up:
> 
> ```
> ./sexpect -s /tmp/sp.sock send -file - -limit 32 | dmenu
> ```

sexpect's `send` sub-command is not supposed to output any meaningful data. It makes little sense to pipe the output to another command. I know nothing about the `dmenu` command so what's your expectation here?

**Comment by vaygr** [comment]
> Shell's `<(cmd)` is not a FD. It's a pathname, as is `/dev/fd/63` in the error message.

Yeah, this is what I'm saying. Maybe accept FD paths as well here?

**Comment by vaygr** [comment]
> sexpect's `send` sub-command is not supposed to output any meaningful data. It makes little sense to pipe the output to another command. According to your previous comments, you may want this:
> 
> ```
> ./sexpect -s /tmp/sp.sock send -file <(dmenu) -limit 32
> # OR
> ./sexpect -s /tmp/sp.sock send -fd 0 -limit 32 < <(dmenu)
> # OR 
> dmenu | ./sexpect -s /tmp/sp.sock send -fd 0 -limit 32
> ```

Yeah, sorry, I confused mismatched the commands. This worked:

```
$ dmenu <&- | ./sexpect -s /tmp/sp.sock send -cr -file - -limit 32
```

**Comment by vaygr** [comment]
> > Shell's `<(cmd)` is not a FD. It's a pathname, as is `/dev/fd/63` in the error message.
> 
> Yeah, this is what I'm saying. Maybe accept FD paths as well here?

Ignore this. Given that you removed regular file check, as you said in your previous comment `-file` works perfectly with a path:

```
$ ./sexpect -s /tmp/sp.sock send -file <(dmenu) -cr -limit 32
```

**Comment by clarkwang** [comment]
> > Shell's `<(cmd)` is not a FD. It's a pathname, as is `/dev/fd/63` in the error message.
> 
> Yeah, this is what I'm saying. Maybe accept FD paths as well here?

The *FD paths* are also files. So usage like `send -file /dev/fd/0 -limit 32` would just work fine.

**Comment by vaygr** [comment]
Yep, see my previous comment. I think all is good now and works as expected.

**Comment by clarkwang** [comment]
Merged to *master*: https://github.com/clarkwang/sexpect/releases/tag/v2.3.12

**Comment by vaygr** [comment]
Thanks a lot! I also submitted an [AUR package](https://aur.archlinux.org/packages/sexpect) and will keep maintaining it. Hopefully that'll increase popularity of this useful tool.
